# Generated by Django 2.2.6 on 2019-10-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertySale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotModel',
            fields=[
                ('Plot_number', models.IntegerField()),
                ('Road_number', models.IntegerField()),
                ('Survey_number', models.IntegerField(primary_key=True, serialize=False)),
                ('Square_yards', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Cost_per_saqare_yard', models.DecimalField(decimal_places=2, max_digits=50)),
                ('Other_expences', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Facing', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('Total_cost', models.DecimalField(decimal_places=2, max_digits=50)),
                ('Plot_image', models.FileField(upload_to='images/')),
            ],
        ),
    ]
