# Generated by Django 2.2.6 on 2019-10-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertySale', '0002_plotmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentModel',
            fields=[
                ('Flat_number', models.IntegerField()),
                ('Road_number', models.IntegerField()),
                ('House_number', models.IntegerField(primary_key=True, serialize=False)),
                ('Square_yards', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Cost', models.DecimalField(decimal_places=2, max_digits=50)),
                ('Other_expences', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Facing', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('Flat_image', models.FileField(upload_to='images/')),
            ],
        ),
    ]
