# Generated by Django 2.2.6 on 2019-10-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertySale', '0003_apartmentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentmodel',
            name='Place',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
