# Generated by Django 2.2.6 on 2019-10-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertySale', '0005_remove_apartmentmodel_other_expences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentmodel',
            name='Flat_image',
            field=models.FileField(upload_to='flatimages/'),
        ),
    ]
