# Generated by Django 2.2.6 on 2019-10-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertySale', '0006_auto_20191028_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=70)),
                ('Designation', models.CharField(max_length=70)),
                ('Employee_mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
